Repository robot-lab/judyst-web-crawler, pull requests merged in 2018-10, with the labels that each got.

#6 Transform ksrf web source
  dist/web_crawler-0.1-py3-none-any.whl
  web_crawler/ksrf.py
Labels: type/code maintenance, type/task

#16 Fixing bug and template
  .github/ISSUE_TEMPLATE/bug_report.md
  dist/web_crawler-0.1-py3-none-any.whl
  dist/web_crawler-0.1.tar.gz
  web_crawler/__init__.py
  web_crawler/__main__.py
  web_crawler/ksrf.py
  web_crawler/tools.py
  web_crawler/web_crawler.py
Labels: priority/high

#17 Changed work with duplicate headers closes #13
  dist/web_crawler-0.1-py3-none-any.whl
  dist/web_crawler-0.1.tar.gz
  web_crawler/ksrf.py
Labels: type/code maintenance
